apiVersion: v1
kind: Secret
metadata:
  name: todolist-secrets
  namespace: gp-2
type: Opaque
data:
  # "postgres" en base64
  postgres-password: cG9zdGdyZXM=
  # "postgresql://postgres:postgres@postgres-service:5432/todolist" en base64
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi90b2RvbGlzdA==
  # Clé JWT — à remplacer en production par: openssl rand -base64 32
  # "change_this_secret_key_in_production_use_openssl_rand" en base64
  jwt-secret-key: Y2hhbmdlX3RoaXNfc2VjcmV0X2tleV9pbl9wcm9kdWN0aW9uX3VzZV9vcGVuc3NsX3JhbmQ=
